name: Export Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull python:3.12

      - name: Export Docker image
        run: docker save python:3.12 -o python_3.12.tar

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ./python_3.12.tar
